python -W ignore train.py \
    --batch_size 16 \
    --input_att_dir '/data/ethanwang/projects/image-paragraph-captioning/data/parabu_att' \
    --input_fc_dir '/data/ethanwang/projects/image-paragraph-captioning/data/parabu_fc' \
    --input_json 'data/paratalk/paratalk.json' \
    --input_label_h5 'data/paratalk/paratalk_label.h5' \
    --language_eval 1 \
    --learning_rate 5e-4 \
    --learning_rate_decay_start -1 \
    --scheduled_sampling_start -1 \
    --max_epochs 60 \
    --rnn_type 'lstm' \
    --input_encoding_size 768 \
    --val_images_use 5000 \
    --save_checkpoint_every 700 \
    --checkpoint_path 'bert_test/hcovtopdown' \
    --caption_model hcovtopdown \
    --id 'bert' \
    --print_freq 300 \
    --beam_size 1 \
    #--start_from 'bert_test/hcovtopdown'
